language: node_js
cache:
  directories:
  - node_modules
env:
  global:
   - CXX=g++-4.8
matrix:
  include:
    - node_js: "6"
      env: GRUNT_TASK=browsers_tests
    - node_js: "7"
      env: GRUNT_TASK=unit_tests
    - node_js: "6"
      env: GRUNT_TASK=unit_tests COVERAGE=true DEPLOY=true
    - node_js: "4"
      env: GRUNT_TASK=unit_tests
    - node_js: "7"
      env: GRUNT_TASK=node_integration_tests
    - node_js: "6"
      env: GRUNT_TASK=node_integration_tests
    - node_js: "4"
      env: GRUNT_TASK=node_integration_tests
  allow_failures:
    - node_js: "6"
      env: GRUNT_TASK=browsers_tests
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
before_install:
  - travis_retry npm install -g grunt-cli
install:
  - travis_retry npm install
before_script:
  - grunt build
script:
  - grunt $GRUNT_TASK
deploy:
  - provider: npm
    email: shahar.soel@gmail.com
    api_key:
      secure: k7juzhofg3lWLolMOIQ6AM0xKYLaRc0MAlGO3sbm2ZFZlGdmXuayHGAD+UL1Vi+KXLfU14fwvIjCpkWc6EWezcFkTG2cxoIC+NpUygQ0z3/E1ylCYM5NU23J+bDtv9xcj5bhNQ/611kHahtIH9DNbY1BbsL0lMH6KwbLDXYUlzk=
    on:
      tags: true
      all_branches: true
      condition: $DEPLOY = true
    skip_cleanup: true

  - provider: script
    script: grunt coveralls:publish
    on:
      condition: $DEPLOY = true
      branch: master
    skip_cleanup: true
notifications:
  email: false