language: node_js
env:
  global:
   - CXX=g++-4.8
cache:
  directories:
    - node_modules
matrix:
  include:
    - node_js: "9"
      env: NPM_TASK=ci_full_build_coveralls DEPLOY=true
    - node_js: "9"
      env: NPM_TASK=ci_browser_tests
    - node_js: "8"
      env: NPM_TASK=ci_full_build
    - node_js: "6"
      env: NPM_TASK=ci_full_build
  allow_failures:
    - node_js: "9"
      env: NPM_TASK=ci_browser_tests
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - yarn
script:
  - yarn run $NPM_TASK
deploy:
  - provider: script
    script: bash scripts/deploy.sh
    on:
      tags: true
      all_branches: true
      condition: $DEPLOY = true
    skip_cleanup: true
notifications:
  email: false
