language: node_js
env:
  global:
   - CXX=g++-4.8
cache:
  directories:
    - node_modules
matrix:
  include:
    - node_js: "9"
      env: NPM_TASK=ci_full_build_coveralls DEPLOY=true
    - node_js: "9"
      env: NPM_TASK=ci_browser_tests
    - node_js: "8"
      env: NPM_TASK=ci_full_build
    - node_js: "6"
      env: NPM_TASK=ci_full_build
  allow_failures:
    - node_js: "8"
      env: NPM_TASK=ci_browser_tests
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
install:
  - npm install
script:
  - npm run $NPM_TASK
deploy:
  - provider: npm
    email: shahar.soel@gmail.com
    api_key:
      secure: k7juzhofg3lWLolMOIQ6AM0xKYLaRc0MAlGO3sbm2ZFZlGdmXuayHGAD+UL1Vi+KXLfU14fwvIjCpkWc6EWezcFkTG2cxoIC+NpUygQ0z3/E1ylCYM5NU23J+bDtv9xcj5bhNQ/611kHahtIH9DNbY1BbsL0lMH6KwbLDXYUlzk=
    on:
      tags: true
      all_branches: true
      condition: $DEPLOY = true
    skip_cleanup: true
notifications:
  email: false
