language: node_js
sudo: required
dist: trusty
cache:
  directories:
  - node_modules
env:
  global:
   - CXX=g++-4.8
matrix:
  include:
    - node_js: "5"
      env: GRUNT_TASK=browsers_unit_tests
    #   seems like Travis + karma + chrome + many different karma tests can cause random faliures with
    #   "some of your tests did a full page reload" or random lockups
    - node_js: "5"
      env: GRUNT_TASK=browsers_integration_tests
    - node_js: "5"
      env: GRUNT_TASK=browsers_integration_tests2
    - node_js: "5"
      env: GRUNT_TASK=unit_tests DEPLOY=true
    - node_js: "4"
      env: GRUNT_TASK=unit_tests
    - node_js: "0.12"
      env: GRUNT_TASK=unit_tests
    - node_js: "0.10"
      env: GRUNT_TASK=unit_tests
    - node_js: "5"
      env: GRUNT_TASK=node_integration_tests
    - node_js: "4"
      env: GRUNT_TASK=node_integration_tests
    - node_js: "0.12"
      env: GRUNT_TASK=node_integration_tests
    - node_js: "0.10"
      env: GRUNT_TASK=node_integration_tests
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
  firefox: latest
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - travis_retry npm install -g grunt-cli
  - sudo apt-get update
  - sudo apt-get install -y libappindicator1 fonts-liberation
  - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
  - sudo dpkg -i google-chrome*.deb
  - export CHROME_BIN=/usr/bin/google-chrome
install:
 - npm install
before_script:
 - grunt build
script:
 - grunt $GRUNT_TASK
deploy:
  - provider: releases
    api_key:
      secure: DNq1wbqLPHVpJPDx9O89HZM+RJB6v2R7/wk8pok7Z8NT72kUWdvbqcThGhczPO4sZ8cUTJ3ergTCE8hs9mynlR/lX6932U4fj4+uICQL9+G+deBB/t2SNyTBllkE64WrJ9BKmQvIk/Chh7ZJOM0Fro3p2BIq3JsVnfYg1tZ3U5o=
    file:
      - package/chevrotain-binaries-0.5.18.zip
      - package/chevrotain-binaries-0.5.18.tar.gz
    on:
      tags : true
      all_branches: true
      condition: $DEPLOY = true
    skip_cleanup: true

  - provider: npm
    email: shahar.soel@gmail.com
    api_key:
      secure: k7juzhofg3lWLolMOIQ6AM0xKYLaRc0MAlGO3sbm2ZFZlGdmXuayHGAD+UL1Vi+KXLfU14fwvIjCpkWc6EWezcFkTG2cxoIC+NpUygQ0z3/E1ylCYM5NU23J+bDtv9xcj5bhNQ/611kHahtIH9DNbY1BbsL0lMH6KwbLDXYUlzk=
    on:
      tags: true
      all_branches: true
      condition: $DEPLOY = true
    skip_cleanup: true

  - provider: script
    script: grunt coveralls:publish
    on:
      condition: $DEPLOY = true
      branch: master
    skip_cleanup: true
notifications:
  email: false