version: 2
jobs:
  build-node16:
    docker:
      - image: circleci/node:16-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run build
      - run: yarn run test

  build-node14:
    docker:
      - image: circleci/node:16-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run build
      - run: yarn run test

  build-node12:
    docker:
      - image: circleci/node:16-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run build
      - run: yarn run test

  deploy:
    docker:
      - image: circleci/node:16-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - run: yarn
      - run: yarn run build
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      # To help debug when lerna detects changes to the working tree
      - run: git status
      # the yarn.lock and some other generated files may change due to running
      # the build with the newly commited version numbers
      # e.g: https://circleci.com/gh/chevrotain/chevrotain/159
      # resetting the working tree avoids lerna errors due to unclean working trees
      - run: git reset --hard
      - run: yarn run lerna:publish

workflows:
  version: 2
  build:
    jobs:
      - build-node16
      - build-node14
      - build-node12
      - deploy:
          filters:
            tags:
              only: /^v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
