version: 2
jobs:
    build-node11:
        docker:
            - image: circleci/node:11-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn
            - run: yarn run build
            - run: yarn run test

    build-node10:
        docker:
            - image: circleci/node:10-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn
            - run: yarn run build
            - run: yarn run test

    build-node8:
        docker:
            - image: circleci/node:8-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn
            - run: yarn run build
            - run: yarn run test

    deploy:
        docker:
            - image: circleci/node:10-browsers
        working_directory: ~/repo
        steps:
            - checkout
            - run: yarn
            - run: yarn run build
            - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
            # To help debug when lerna detects changes to the working tree
            - run: git status
            - run: yarn run lerna:publish

workflows:
    version: 2
    build:
        jobs:
            - build-node11
            - build-node10
            - build-node8
            - deploy:
                  filters:
                      tags:
                          only: /^v[0-9]+(\.[0-9]+)*/
                      branches:
                          ignore: /.*/
